### ISSUE TITLE
SSLHandshakeException unter älteren Android Versionen mit neuem Server

### ISSUE THREAD

**Issue by GlaserDaniel** [HochschuleHofStundenplanapp/AndroidStundenplanHof#16]
Beim Abholen der Daten vom neuen Server kommt unten stehende SSLHandshakeException und deswegen keine Daten.

Tritt unter Android 4.3 und 4.1.2 auf. Bei 7.1.1 klappt alles einwandfrei.
Erste Vermutung war Umstellung auf neue Play Services, aber hab ich zurück gestellt und kommt trotzdem noch. Auch die anderen neuen Dependecies hab ich mal zurück gestellt, hilft aber nichts. 
Ich teste mal als nächstes ob es mit dem alten Server funktioniert.

E/DataConnector: readStringFromUrl: IOExcepton: 
                 javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                     at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:401)
                     at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:209)
                     at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:478)
                     at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:433)
                     at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:290)
                     at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:240)
                     at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:282)
                     at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:177)
                     at libcore.net.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:271)
                     at de.hof.university.app.data.DataConnector.readStringFromUrl(DataConnector.java:133)
                     at de.hof.university.app.data.DataConnector.getStringFromUrl(DataConnector.java:53)
                     at de.hof.university.app.data.DataManager.getData(DataManager.java:360)
                     at de.hof.university.app.data.DataManager.getCourses(DataManager.java:318)
                     at de.hof.university.app.fragment.settings.SettingsFragment$GetSemesterTask.doInBackground(SettingsFragment.java:411)
                     at de.hof.university.app.fragment.settings.SettingsFragment$GetSemesterTask.doInBackground(SettingsFragment.java:389)
                     at android.os.AsyncTask$2.call(AsyncTask.java:287)
                     at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                     at java.lang.Thread.run(Thread.java:841)
                  Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                     at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:282)
                     at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:202)
                     at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:608)
                     at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
                     at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:398)
                     at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:209) 
                     at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:478) 
                     at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:433) 
                     at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:290) 
                     at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:240) 
                     at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:282) 
                     at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:177) 
                     at libcore.net.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:271) 
                     at de.hof.university.app.data.DataConnector.readStringFromUrl(DataConnector.java:133) 
                     at de.hof.university.app.data.DataConnector.getStringFromUrl(DataConnector.java:53) 
                     at de.hof.university.app.data.DataManager.getData(DataManager.java:360) 
                     at de.hof.university.app.data.DataManager.getCourses(DataManager.java:318) 
                     at de.hof.university.app.fragment.settings.SettingsFragment$GetSemesterTask.doInBackground(SettingsFragment.java:411) 
                     at de.hof.university.app.fragment.settings.SettingsFragment$GetSemesterTask.doInBackground(SettingsFragment.java:389) 
                     at android.os.AsyncTask$2.call(AsyncTask.java:287) 
                     at java.util.concurrent.FutureTask.run(FutureTask.java:234) 
                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230) 
                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
                     at java.lang.Thread.run(Thread.java:841) 
                  Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                     at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:282) 
                     at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:202) 
                     at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:608) 
                     at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method) 
                     at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:398) 
                     at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:209) 
                     at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:478) 
                     at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:433) 
                     at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:290) 
                     at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:240) 
                     at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:282) 
                     at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:177) 
                     at libcore.net.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:271) 
                     at de.hof.university.app.data.DataConnector.readStringFromUrl(DataConnector.java:133) 
                     at de.hof.university.app.data.DataConnector.getStringFromUrl(DataConnector.java:53) 
                     at de.hof.university.app.data.DataManager.getData(DataManager.java:360) 
                     at de.hof.university.app.data.DataManager.getCourses(DataManager.java:318) 
                     at de.hof.university.app.fragment.settings.SettingsFragment$GetSemesterTask.doInBackground(SettingsFragment.java:411) 
                     at de.hof.university.app.fragment.settings.SettingsFragment$GetSemesterTask.doInBackground(SettingsFragment.java:389) 
                     at android.os.AsyncTask$2.call(AsyncTask.java:287) 
                     at java.util.concurrent.FutureTask.run(FutureTask.java:234) 
                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230) 
                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
                     at java.lang.Thread.run(Thread.java:841)

**Comment by GlaserDaniel** [comment]
Jep. Mit dem alten Server geht es wieder. Also nur die URL geändert und geht es wieder. Das heißt dann wohl das es am Server liegt. Wohl mal dem Herr Karl schreiben.

**Comment by GlaserDaniel** [comment]
Jep. Lag an dem Zertifikat des Servers. Ist nun ein Cross-Zertifikat-Chain aktiviert und jetzt geht es auch wieder unter Android Versionen die älter als Android 5.0 sind. Zumindest bis 2019. 😊
