### ISSUE TITLE
Absturz beim Login Dialog 

### ISSUE THREAD

**Issue by GlaserDaniel** [HochschuleHofStundenplanapp/AndroidStundenplanHof#2]
Die App stürzt manchmal ab wenn der Login Dialog kommen sollte.

**Comment by GlaserDaniel** [comment]
Diese Fehlermeldung könnte damit zu tun haben:
Fatal signal 11 (SIGSEGV), code 1, fault addr 0x1 in tid 8871 (.university.app)
Kam als ich auf Abbrechen im Login Dialog gedrückt habe.

**Comment by GlaserDaniel** [comment]
Das ist die bessere Fehlermeldung:
de.hof.university.app E/AndroidRuntime: FATAL EXCEPTION: main
	Process: de.hof.university.app, PID: 32686
	Theme: themes:{default=overlay:com.blazze11.euphoria.dark, iconPack:com.benx9.palmtree, 
		fontPkg:system, com.android.systemui=overlay:cm.theme.transparentblack}
	android.view.WindowManager$BadTokenException: Unable to add window -- 
		token android.os.BinderProxy@22d9de1 is not valid; is your activity running?
		at android.view.ViewRootImpl.setView(ViewRootImpl.java:571)
		at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
		at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:86)
		at android.app.Dialog.show(Dialog.java:319)
		at de.hof.university.app.experimental.LoginController.showLoginDialog(LoginController.java:185)
		at de.hof.university.app.fragment.settings.SettingsFragment$2.onPreferenceClick(SettingsFragment.java:90)
		at android.preference.Preference.performClick(Preference.java:996)
		at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
		at android.widget.AdapterView.performItemClick(AdapterView.java:310)
		at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
		at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
		at android.widget.AbsListView$3.run(AbsListView.java:3903)
		at android.os.Handler.handleCallback(Handler.java:739)
		at android.os.Handler.dispatchMessage(Handler.java:95)
		at android.os.Looper.loop(Looper.java:148)
		at android.app.ActivityThread.main(ActivityThread.java:5461)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
		at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)


Mögliche Lösung die ich eingebaut habe:
if (isVisible()) { //nur wenn die Activity sichtbar ist den Dialog anzeigen
	loginController.showLoginDialog();
	return true;
} else {
	return false;
}

**Comment by GlaserDaniel** [comment]
Ok. Fehler scheint immer noch zu sein. :-(

**Comment by avinotec** [comment]
erledigt
